name: emotion
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.55.2
  flutter_svg: ^1.1.5
  adaptive_action_sheet: ^2.0.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  file_picker: ^5.2.0+1
  http_parser: ^4.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  oktoast: ^3.3.1
  provider: ^6.0.3
  http: ^0.13.5
  crypto: ^3.0.2
  flutter_slidable: ^2.0.0
  photo_view: ^0.14.0
  crop_your_image: ^0.7.2
  flutter_bounce: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/